# Generated by Django 3.1.3 on 2020-11-16 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_auto_20201114_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_id', models.CharField(max_length=10)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.movie')),
            ],
        ),
    ]
